name: PostgreSQL service
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:18

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client
        run: apt-get update && apt-get install -y postgresql-client

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build
      
      - name: Set up the database
        run: |
          psql -h postgres -U user -d postgres -a -f ./db/dump_techchallengeposts.sql
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Connect to PostgreSQL
        run: node dist/src/server.js
        env:
          HOST: 0.0.0.0
          PORT: 3000
          ENV: production
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
          DATABASE_USER: user
          DATABASE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_NAME: techchallengeposts
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
