name: PostgreSQL service
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:18

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: node ../app.ts
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: user
          POSTGRES_PASSWORD: postgres
          JWT_SECRET: batman
